### ISSUE TITLE
New environment creation request

### ISSUE THREAD

**Issue by aydjay** [PostgresCompare/postgrescompare-issues#1]
Small feature request - when creating a new environment, it asks me which database I would like to connect too. I don't know the name of the database 100% of the time so after i've "Tested" the connection if it could show me a list of available databases that would be great.

**Comment by sql-migrate** [comment]
Thanks for the feedback Alex, and for being the first person to open an issue :)

I've had this request a few times so I'll get on it asap.

**Comment by digason** [comment]
Even better, the database should be tied to the project, not the environment. I might have multiple projects in the same environment, but the database name won't have the same across projects. The current method forces me to create a new environment for each project, which seems to defeat the purpose of separating environment from project.

**Comment by sql-migrate** [comment]
Thought about it and this is a great suggestion, it also gives me a place to put the ability to select not only the database but a particular schema to compare too! Thanks

**Comment by sql-migrate** [comment]
@aydjay, @digason the latest version of PostgresCompare (1.0.34-alpha) implements both of these suggestions. The new environment has a default database field that lists available options and when creating a project one can specify a different database than the default to compare. Please try it out and let me know anything else you run into! Thanks!
