### ISSUE TITLE
New Sequences not appearing in "New Script" window

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#11]
Version 1.0.52

I've got a compare that noticed new sequences in the source db.  When going to the SQL deploy step, i notice they're not an option to generate sql for.

![image](https://user-images.githubusercontent.com/2199565/59136448-14b39c80-8938-11e9-8e0b-ba2d5ca85fb4.png)

**Comment by mhov** [comment]
@neilanderson sorry for issue spamming you.   I've encountered all of today's issues trying to do a single (but difficult) migration.

**Comment by sql-migrate** [comment]
@mhov don't apologize, this is great! There's so much ground to cover I need people like yourself to let me know when the SQL isn't correct.

**Comment by sql-migrate** [comment]
fixed in 1.0.53
