### ISSUE TITLE
ARROW_BACK button in New Script modal

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#12]
Version 1.0.53

1. Start a compare
2. Open a New Script modal 
3. Expand the window to full screen

You'll see a button that normally hides in smaller responsive views, missing it's proper name/icon, and unceremoniously closes the script window when clicked.

![image](https://user-images.githubusercontent.com/2199565/59211611-1a41fa00-8b65-11e9-9ecb-11eefcdb54ec.png)

**Comment by sql-migrate** [comment]
hmm, I cant replicate yet. There's usually just an arrow icon there and a floppy icon.
