### ISSUE TITLE
Partial Index conditions not respected

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#13]
Version 1.1.11

When my source looks like
> CREATE INDEX my_index
>     ON my_table(my_bool)
>     WHERE NOT my_bool

I get this in the deploy script
> CREATE INDEX my_index
>     ON my_table(my_bool)

Seems to be missing the conditional of the partial index

**Comment by sql-migrate** [comment]
👍 ty

**Comment by sql-migrate** [comment]
fixed in next version
