### ISSUE TITLE
Creating Partitioned Tables has Incorrect Syntax

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#14]
Version 1.1.11

Source looks like 

> CREATE TABLE my_partition_table
> (
>     partition_column int,
>     ....
> )
> PARTITION BY LIST ( partition_column);

What comes through the deploy sql is

> CREATE TABLE my_partition_table
> (
>     partition_column int,
>     ....
> )
> TABLESPACE pg_default
> PARTITION BY LIST ( partition_column);

Where the TABLESPACE's position is incorrect. Probably should come after PARTITION BY according to the docs.

**Comment by sql-migrate** [comment]
👍

**Comment by sql-migrate** [comment]
fixed in next version
