### ISSUE TITLE
Dropping Procedure results in Drop Function script

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#15]
Version: 1.1.20
PG: 11.x

If i'm dropping a Procedure between db A & B. The script generates as
`DROP FUNCTION mySchema.myProcedure ( params)`
Expecting 
`DROP PROCEDURE mySchema.myProcedure ( params)`

**Comment by sql-migrate** [comment]
Thanks @mhov, I believe this was fixed in 1.1.27
