### ISSUE TITLE
Feature Request:  Grid/Tables instead of Cards

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#16]
Once one gets more than a couple environments/projects the visual layout of cards becomes less helpful.  Could we get the option to display these views in a tabular/grid format instead. It would make it much easier to organize/find things.  (column sorting would be a nice to have)

![image](https://user-images.githubusercontent.com/2199565/73982932-162fcd00-48ea-11ea-8065-c6f74f9a0cdb.png)

Thanks Neil!

**Comment by sql-migrate** [comment]
This is on the way @mhov!

**Comment by mhov** [comment]
thanks Neil, looks great any chance to get the context menu options for the List table rows? (Compare/Edit/Copy/Start Sharing/Delete)
