### ISSUE TITLE
Progress bar in deployment modal incorrect

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#17]
Version: 1.1.32

After I deploy changes (usually a subset of all compared changes) recently the progress modal doesn't actually complete once the deployment finishes. It will be stuck in a state like below:

![image](https://user-images.githubusercontent.com/2199565/77474822-01919080-6dd5-11ea-9f63-0faab68a60d5.png)

**Comment by sql-migrate** [comment]
fixed!
