### ISSUE TITLE
Incorrect comparison on triggers

### ISSUE THREAD

**Issue by digason** [PostgresCompare/postgrescompare-issues#2]
Comparison seems to only account for the trigger name, ignoring the context of the table, and causing the trigger declarations to be detected as a difference. Instead, triggers should only be considered for comparison if they belong to the same table.
![screen shot 2018-12-17](https://user-images.githubusercontent.com/3792455/50118026-17002e00-0214-11e9-95f2-fd54da8e8ed4.png)

**Comment by sql-migrate** [comment]
Hi, I was all set to say how that's a legit difference but looking at https://www.postgresql.org/docs/current/catalog-pg-trigger.html you're right, the name is only required to be unique among triggers on the same table. Thanks for the report 
@digason . I'll fix it asap :)

**Comment by sql-migrate** [comment]
Fixed in 1.0.42-beta, ty @digason
