### ISSUE TITLE
The problem of query uppercase fields

### ISSUE THREAD

**Issue by minh656644** [PostgresCompare/postgrescompare-issues#3]
![Screenshot from 2019-03-12 11-24-29](https://user-images.githubusercontent.com/35527305/54174714-78a20280-44ba-11e9-8564-f66aa19227f9.png)

If I query with CompanyID, the query is wrong. It must be correct to "CompanyID".

**Comment by sql-migrate** [comment]
Hi @minh656644 I see that I'm not quoting the CompanyID correctly in the CREATE INDEX statement. I'll fix that. Thanks!

**Comment by sql-migrate** [comment]
Fixed in the upcoming release
