### ISSUE TITLE
Can't create a deploy script from a compare

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#4]
I did a fresh first-time install of v1.0.49 and ran up against this problem
Steps

1. Fresh install of 1.0.49
2. Added 2 environments
3. Created a project
4. Performed a Compare  (differences looked accurate)
5. Pressed "SQL Script" (also tried from Deployments Tab)

What I saw: An incorrectly initiated "New Script" Dialog, missing the source/target environment, the results of the compare, and the Comparison field is empty with no way to select a comparison.  (screenshot below)

What I expect: A dialog window with the results of the current Compare, as in the demo video/documentation.

![image](https://user-images.githubusercontent.com/2199565/57801957-ce3c9a80-7709-11e9-92ae-78953ee5fc40.png)

**Comment by neilanderson** [comment]
Hi, thanks for reporting this. There must be an error thrown during the script generation. Could you send me the log (neil@postgrescompare.com) ? on Windows that would be in %APPDATA%/Roaming/PostgresCompare/Logs

**Comment by sql-migrate** [comment]
Hi, thanks for reporting the issue and sending me the extra info. I believe I've fixed it and I'll be shipping it in the next release this week.

**Comment by sql-migrate** [comment]
and it's out now, thanks for the report and any further issues just let me know please.
