### ISSUE TITLE
Deployment progress incorrect for partial deployment

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#5]
If i create a deployment and then choose only some of the differences, the progress dialog seems to count all the unselected changes

![image](https://user-images.githubusercontent.com/2199565/58737773-b7f43700-83b7-11e9-9ddd-967c9c5f7139.png)

I would expect it to count 3 changes with a full progress bar.

Changes seemed to go over correctly, so this is just a cosmetic issue.

**Comment by sql-migrate** [comment]
ty @mhov, fixed in v1.0.52 (I'm still counting the Begin and Commit as a "change" for now though)
