### ISSUE TITLE
Drop Function statment oddly quoted

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#6]
Using Version 1.0.52

I'm doing a compare in which the target db needs to drop a function, the deploy SQL generated as 
`DROP FUNCTION some_schema."some_func(p_id integer)";`
which results in 
`ERROR: could not find a function named "some_schema.some_func(p_div_id integer)" SQL state: 42883`

Removing the quotes does work when run manually
`DROP FUNCTION some_schema.some_func(p_id integer);`

**Comment by sql-migrate** [comment]
not released yet, but fixed so closing just to keep track
