### ISSUE TITLE
Can't modify function referencing a table change from later in same compare

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#8]
Using Version 1.0.52

Say in my compare I have 2 changes:

1. Adding a new column `new_column` to a table `my_table`
2. Changing `my_func()`  to reference `new_column`

If the SQL deploy script executes the `Create or Replace Function` step before `Add Column` I'll see `42703: column new_column does not exist`.

I'm not sure if there's a natural order to how these changes get ordered in a deploy, would it be safe to always deploy table changes before function/procedure changes?

**Comment by sql-migrate** [comment]
Dependency tracking doesn't include objects that the body of the function refers to so I think the best we can do is move it to the end of the script and hope!
