### ISSUE TITLE
Arrays of user-defined types not rendered properly in functions

### ISSUE THREAD

**Issue by mhov** [PostgresCompare/postgrescompare-issues#9]
Using Version 1.0.52, PG 11.2

Where my source has 
```
CREATE TYPE some_schema.kv_int AS ( k integer, v integer );
CREATE FUNCTION some_schema.sort_kv_to_array(p_input some_schema.kv_int[]) ..
```
The deploy SQL tries to update the function as
```
CREATE FUNCTION some_schema.sort_kv_to_array ( p_input _kv_int )
```

looks like it's trying to _array-ify_ the input type (ex `int4[]` -> `_int4`) but for a user-defined type with a schema, it's not working, expecting to remain `some_schema.kv_int[]`

**Comment by sql-migrate** [comment]
fixed in 1.053

**Comment by mhov** [comment]
Hi Neil.  So I checked out the fix and it's partially working now
Instead of 
```
CREATE FUNCTION some_schema.sort_kv_to_array ( p_input _kv_int )
```
I get 
```
CREATE FUNCTION some_schema.sort_kv_to_array( p_input kv_int [ ] )  ..
```
When I'd expect
```
CREATE FUNCTION some_schema.sort_kv_to_array(p_input some_schema.kv_int[])
```

I use a quite a bit of non-public (or `search_path`) schemas in my work so I realize it's not the common test case.

**Comment by sql-migrate** [comment]
ah I see, yeah I'm not including the schema name

**Comment by sql-migrate** [comment]
should be fixed in the next release
